import Link from "next/link";
import { Building2, MapPin, MessageCircle, Wrench } from "lucide-react";
import { EmptyState, PageHeader, StatusPill } from "@/components/portal/PortalUI";
import { requireEmployeeContext } from "@/lib/portal/access";

function relation<T>(value: T | T[] | null | undefined): T | null { return Array.isArray(value) ? value[0] ?? null : value ?? null; }

export default async function EmployeePropertiesPage() {
  const { employee, supabase } = await requireEmployeeContext();
  const { data: assignments } = await supabase.from("property_employee_assignments").select("property_id,properties(id,name,status,buildings(id,label,formatted_address),property_services(id,status))").eq("employee_id", employee.id).eq("active", true);
  return <><PageHeader eyebrow="Meine Immobilien" title="Zugewiesene Objekte" text="Adressen, Briefings, Chat und operative Meldungen Ihrer aktuellen Zuweisungen." />{assignments?.length ? <div className="grid gap-4 md:grid-cols-2">{assignments.map((assignment) => { const property = relation(assignment.properties) as { id: string; name: string; status: string; buildings: { id: string; label: string | null; formatted_address: string }[]; property_services: { id: string; status: string }[] } | null; if (!property) return null; return <Link key={property.id} href={`/app/properties/${property.id}`} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-brand hover:shadow-lg"><div className="flex items-start justify-between gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-brand-soft text-brand"><Building2 size={22} /></span><StatusPill>{property.status === "active" ? "Aktiv" : property.status}</StatusPill></div><h2 className="mt-4 text-xl font-black text-slate-950 group-hover:text-brand">{property.name}</h2><div className="mt-3 grid gap-2 text-sm text-slate-600">{property.buildings?.slice(0, 2).map((building) => <p key={building.id} className="flex items-start gap-2"><MapPin size={16} className="mt-0.5 shrink-0" /> {building.label ? `${building.label}: ` : ""}{building.formatted_address}</p>)}</div><div className="mt-4 flex gap-3 text-xs font-black text-slate-500"><span className="flex items-center gap-1"><Wrench size={14} /> {property.property_services?.filter((service) => service.status === "active").length ?? 0} Leistungen</span><span className="flex items-center gap-1"><MessageCircle size={14} /> Chat</span></div></Link>; })}</div> : <EmptyState title="Keine Immobilien zugewiesen" text="Ihre aktiven Objektzuweisungen erscheinen hier." />}</>;
}
