import { Clock3 } from "lucide-react";
import { EmptyState, PageHeader, Panel, StatusPill, inputClass } from "@/components/portal/PortalUI";
import { berlinDateParts, formatGermanDate } from "@/lib/portal/core";
import { requireEmployeeContext } from "@/lib/portal/access";

function relation<T>(value: T | T[] | null | undefined): T | null { return Array.isArray(value) ? value[0] ?? null : value ?? null; }

export default async function EmployeeTimePage({ searchParams }: { searchParams: Promise<{ month?: string }> }) {
  const { month } = await searchParams; const now = berlinDateParts(); const selected = /^\d{4}-\d{2}$/.test(month ?? "") ? month! : `${now.year}-${String(now.month).padStart(2, "0")}`; const [year, monthNumber] = selected.split("-").map(Number); const start = `${selected}-01`; const endDate = new Date(Date.UTC(year, monthNumber, 0, 12)).toISOString().slice(0, 10);
  const { profile, supabase } = await requireEmployeeContext(); const { data: visits } = await supabase.from("visits").select("id,scheduled_date,started_at,completed_at,duration_minutes,status,properties(name),visit_buildings(buildings(label,formatted_address))").eq("started_by", profile.id).gte("scheduled_date", start).lte("scheduled_date", endDate).in("status", ["started", "completed"]).order("scheduled_date", { ascending: false }); const total = visits?.reduce((sum, visit) => sum + Number(visit.duration_minutes ?? 0), 0) ?? 0;
  return <><PageHeader eyebrow="Eigene Arbeitszeiten" title="Monatsübersicht" text="Ausschließlich Ihre serverseitig erfassten Einsatzzeiten." /><form className="mb-5 flex max-w-sm items-end gap-3"><label className="flex-1 text-sm font-bold text-slate-800">Monat<input name="month" type="month" defaultValue={selected} className={inputClass} /></label><button className="min-h-11 rounded-xl bg-brand px-4 text-sm font-black text-white">Anzeigen</button></form><div className="mb-5 rounded-2xl bg-brand p-5 text-white shadow-lg"><p className="text-xs font-black uppercase tracking-wide text-blue-200">Monatssumme</p><p className="mt-2 flex items-center gap-2 text-3xl font-black"><Clock3 /> {Math.floor(total / 60)} Std. {total % 60} Min.</p></div><Panel title="Einsätze">{visits?.length ? <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><th className="p-3">Datum</th><th className="p-3">Immobilie</th><th className="p-3">Adresse</th><th className="p-3">Start</th><th className="p-3">Ende</th><th className="p-3">Dauer</th><th className="p-3">Status</th></tr></thead><tbody>{visits.map((visit) => { const property = relation(visit.properties); const building = relation(visit.visit_buildings?.[0]?.buildings); return <tr key={visit.id} className="border-b border-slate-100"><td className="p-3 font-bold">{formatGermanDate(`${visit.scheduled_date}T12:00:00Z`)}</td><td className="p-3">{property?.name}</td><td className="p-3 text-slate-600">{building?.formatted_address}</td><td className="p-3">{visit.started_at ? formatGermanDate(visit.started_at, { hour: "2-digit", minute: "2-digit", day: undefined, month: undefined, year: undefined }) : "–"}</td><td className="p-3">{visit.completed_at ? formatGermanDate(visit.completed_at, { hour: "2-digit", minute: "2-digit", day: undefined, month: undefined, year: undefined }) : "läuft"}</td><td className="p-3 font-black">{Math.floor(Number(visit.duration_minutes ?? 0) / 60)}:{String(Number(visit.duration_minutes ?? 0) % 60).padStart(2, "0")}</td><td className="p-3"><StatusPill>{visit.status === "completed" ? "Abgeschlossen" : "Läuft"}</StatusPill></td></tr>; })}</tbody></table></div> : <EmptyState title="Keine Zeiten im gewählten Monat" text="Abgeschlossene Einsätze erscheinen automatisch in dieser Übersicht." />}</Panel></>;
}
